CREATE TABLE users (user_id BIGSERIAL PRIMARY KEY NOT NULL, username VARCHAR(20) NOT NULL, email VARCHAR(50) NOT NULL,
password VARCHAR(16) NOT NULL);
CREATE TABLE friends (id BIGSERIAL PRIMARY KEY NOT NULL, requester_id BIGINT NOT NULL, requested_id BIGINT NOT NULL);
CREATE TABLE subscribers (id BIGSERIAL PRIMARY KEY NOT NULL, requester_id BIGINT NOT NULL, requested_id BIGINT NOT NULL);
CREATE TABLE subscribed (id BIGSERIAL PRIMARY KEY NOT NULL, requester_id BIGINT NOT NULL, requested_id BIGINT NOT NULL);
CREATE TABLE posts (post_id BIGSERIAL PRIMARY KEY NOT NULL, header VARCHAR(255) NOT NULL, message TEXT,
creation_date_time TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_date_time TIMESTAMP(0) WITH TIME ZONE,
author_id BIGINT NOT NULL, image_path TEXT);
CREATE TABLE images (image_id BIGSERIAL PRIMARY KEY NOT NULL, content BYTEA, post_id BIGINT NOT NULL REFERENCES posts (post_id));
CREATE TABLE friendship_invites (invite_id BIGSERIAL PRIMARY KEY NOT NULL, requester_id BIGINT NOT NULL, requested_id BIGINT NOT NULL);
