CREATE TABLE users (user_id BIGSERIAL PRIMARY KEY NOT NULL, username VARCHAR(20) NOT NULL, email VARCHAR(50) NOT NULL,
password TEXT NOT NULL);
CREATE TABLE friends (id BIGSERIAL PRIMARY KEY NOT NULL, requester_id BIGINT NOT NULL, requested_id BIGINT NOT NULL);
CREATE TABLE subscribers (id BIGSERIAL PRIMARY KEY NOT NULL, requester_id BIGINT NOT NULL, requested_id BIGINT NOT NULL);
CREATE TABLE subscribed (id BIGSERIAL PRIMARY KEY NOT NULL, requester_id BIGINT NOT NULL, requested_id BIGINT NOT NULL);
CREATE TABLE posts (post_id BIGSERIAL PRIMARY KEY NOT NULL, header VARCHAR(255) NOT NULL, message TEXT,
creation_date_time TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_date_time TIMESTAMP(0) WITH TIME ZONE,
author_id BIGINT NOT NULL);
CREATE TABLE mediafiles (file_id BIGSERIAL PRIMARY KEY NOT NULL, filename TEXT NOT NULL, content BYTEA NOT NULL, post_id BIGINT NOT NULL);
CREATE TABLE friendship_invites (invite_id BIGSERIAL PRIMARY KEY NOT NULL, requester_id BIGINT NOT NULL, requested_id BIGINT NOT NULL);
CREATE TABLE role (id BIGSERIAL PRIMARY KEY NOT NULL, name VARCHAR(255) NOT NULL);
INSERT INTO role (id, name) VALUES (1, 'ROLE_USER'), (2, 'ROLE_ADMIN');
